### ISSUE TITLE
super wide raven when opening settings

### ISSUE THREAD

**Issue by fossfreedom** [ilgarmehmetali/budgie-pixel-saver-applet#11]
I'm trying to get the plugin to work under Ubuntu 16.04 - it uses GTK+3.18

I've reduced the settings.ui setting from GTK+3.20 to GTK+3.18

It compiles and works very well under Ubuntu 16.04 - the only problem is when I open settings raven expands hugely.  Any ideas?

![ubuntu xenial dev running - oracle vm virtualbox 1_739](https://cloud.githubusercontent.com/assets/996240/24577682/5d7069ea-16ca-11e7-9da6-a40886838557.png)

**Comment by ilgarmehmetali** [comment]
Didn't know there was a setting for gtk version in glade files.

Raven seems to grow with its children, setting labels are set to wrap with words. Don't know whats causing it not to wrap. Will separate long labels to multiple lines for now.
