### ISSUE TITLE
Support for vertical panels

### ISSUE THREAD

**Issue by jhasse** [ilgarmehmetali/budgie-pixel-saver-applet#23]
When using the applet with a vertical panel (on the left or on the right), the panel becomes too wide. Maybe an option to only show the close button?

**Comment by ilgarmehmetali** [comment]
Thanks for reporting this, i am not using vertical panels so this issue didn't came to my mind.

Have to look how Ikey implemented his vertical applets for title part of this applet, i can think of a way to make buttons work though

Btw, i haven't been able to find time to work on extensions for some time now but i haven't abandoned them :)

**Comment by ilgarmehmetali** [comment]
Did some work on this, it should be usable on vertical panels now.

**Comment by jhasse** [comment]
Works perfectly! Thanks :)
