### ISSUE TITLE
non maximized windows should not display in the panel

### ISSUE THREAD

**Issue by fossfreedom** [ilgarmehmetali/budgie-pixel-saver-applet#3]
![ubuntu budgie - new development snapshot 1 running - oracle vm virtualbox_734](https://cloud.githubusercontent.com/assets/996240/24477177/faf10c64-14cd-11e7-9d99-dd0c1ee42444.png)

apps  that are not maximized you still see the window controls - suggest hide these from the panel.

**Comment by ilgarmehmetali** [comment]
I personally like the applet showing all the time, it prevents other applets from jumping around the panel when another one gets hidden. I might add a setting for this though.

Btw is title not showing for Terminix?

**Comment by fossfreedom** [comment]
the title is not showing because it didnt have focus.

Yeah - I think an option to hide pixel saver for non-maximised windows will make alot of sense - especially for those that don't have icon-task-list applet and therefore there isn't a likelihood of icons moving around.

**Comment by ilgarmehmetali** [comment]
I use this with 2 applets(like the second screenshot from readme), one in the center with title only and one in the corner with buttons only. I'm more worried with applets at the end, for example like volume control.
Ive added a setting for this though.
