### ISSUE TITLE
when removing the applet from the panel, it appears still to be partially working

### ISSUE THREAD

**Issue by fossfreedom** [ilgarmehmetali/budgie-pixel-saver-applet#6]
![ubuntu budgie - new development snapshot 1 running - oracle vm virtualbox_736](https://cloud.githubusercontent.com/assets/996240/24477659/bd009f08-14cf-11e7-9e89-438ce5aff330.png)

I removed the applet from the window - the window decoration didnt reappear - minor issue.

However, when closing the app and reopening the decoration still does not display until you logout/login or run budgie-panel --replace

**Comment by ilgarmehmetali** [comment]
Let me know if this persists and i will reopen the issue.

**Comment by fossfreedom** [comment]
excellent - works nicely now.  cheers
