### ISSUE TITLE
reentrancy assertion

### ISSUE THREAD

**Issue by fossfreedom** [ilgarmehmetali/budgie-pixel-saver-applet#7]
![ubuntu budgie - new development snapshot 1 running - oracle vm virtualbox_738](https://cloud.githubusercontent.com/assets/996240/24520523/b2704f78-1580-11e7-919b-84b35a2f23dc.png)

open raven - then click back on terminix - raven closes and you see the error message in the screenshot

**Comment by ilgarmehmetali** [comment]
I'm not sure whats the couse for this.

**Comment by ilgarmehmetali** [comment]
Can you check if everything works as before with 	https://github.com/ilgarmehmetali/budgie-pixel-saver-applet/commit/de8ab7b61b9d6915466f2e5414f513b381d17187

**Comment by fossfreedom** [comment]
looks good to me :)
