### ISSUE TITLE
missing license file / public email address

### ISSUE THREAD

**Issue by fossfreedom** [ilgarmehmetali/budgie-pixel-saver-applet#8]
please can you add a license file for this project.

I wish to package this for Ubuntu Budgie - and I need this to create a valid package.

Also I note you do not have a public email address in the plugin file.  You don't have to - but again, for debian packaging it is usual to give full acknowledgment of you as the author.

**Comment by ilgarmehmetali** [comment]
Added both, didnt thought about adding mail address to plugin file, thanks for the tip
